title: Just Predict
description: Jump Into Trends
theme: just-the-docs

url: https://pages.predictyourgame.com

color_scheme: custom
favicon_ico: "/Logo.png"  # Update this path if your favicon is in a different location